import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { sassPlugin } from "esbuild-sass-plugin";
import copyStaticFiles from "esbuild-copy-static-files";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod
	? "./dist/"
	: // Assumed local path. Update this to the path of your local development vault
	  "E:/Documents/PersonalObsidianVault/.obsidian/plugins/obsidian-canvas-dailynote/";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts", "styles.scss"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minifySyntax: true,
	plugins: [
		sassPlugin(),
		copyStaticFiles({
			src: "./manifest.json",
			dest: path.join(outdir, "manifest.json"),
		}),
	],
	outdir: outdir,
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
	await context.serve(); // This enables the "live reload"
}
